{{- if and .Values.keypairGenerator.enabled .Values.serviceAccount.create -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "chart.fullname" . }}-keypair-generator
  annotations: 
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "4"
subjects:
  - kind: ServiceAccount
    name: {{ include "chart.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "chart.fullname" . }}-keypair-generator
  apiGroup: rbac.authorization.k8s.io

{{- end }}
