---
name: Deploy Images to GHCR
env: {}
on:
  workflow_dispatch:

jobs:
  push-my-app-image:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "./my-app"
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@main

      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GH_TOKEN}}

      - name: "Build Image"
        run: |
          docker buildx create --use
          docker buildx build --push --platform linux/amd64,linux/arm64 --tag ghcr.io/castorw/techtalk-k8s-202503-my-app:latest .
